package mapreduce

import (
	"encoding/json"
	"fmt"
	"hash/fnv"
	"os"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//

	// Overall Flow：
	// 1. Open file and read data
	// 2. Invoke user-defined mapF function, get key-value slice kv
	// 3. Partition data in slice kv according to the key(use hash() to get index),
	//    create intermediate file (name=reduceName, type=json)
	// 4. Store key-value data to the file specified by hashed key

	f, err := os.Open(inFile)
	defer f.Close()
	if err != nil {
		fmt.Print(err)
		fmt.Println("error opening file")
		return
	}

	finfo, err := f.Stat()
	if err != nil {
		fmt.Print(err)
		fmt.Println("error obtaining file data")
		return
	}

	// create empty slice of bytes
	fcontent := make([]byte, finfo.Size())
	// read bytes into fcontent from opened file
	f.Read(fcontent)
	// convert bytes into string
	contents := string(fcontent)

	// invoke map function from client
	keyvalue := mapF(inFile, contents)
	fjson := make([]*json.Encoder, nReduce)
	files := make([]*os.File, nReduce)

	// create list of intermediate files
	for i := range fjson {
		// generate file name
		filename := reduceName(jobName, mapTask, i)
		file, err := os.Create(filename)
		if err != nil {
			fmt.Print(err)
			fmt.Printf("error creating file %s", filename)
			return
		}
		fjson[i] = json.NewEncoder(file)
		files[i] = file
	}

	// partition files
	for _, kv := range keyvalue {
		index := ihash(kv.Key) % int(nReduce)
		fjson[index].Encode(&kv)
	}

	// close all files
	for _, file := range files {
		file.Close()
	}
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
